name = "SphericoMC"
author = "Spherico Hub"
version = "4.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "787e33534e5f29204f7a211fdba25f998d815c0fe7489a293f844fb50e27516a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
