name = "SphericoMC"
author = "Spherico Hub"
version = "4.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecb60c813f9f138a3641463e70194178b7ae3236c56927d2eaefc0c636adefa8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21"]
