name = "SphericoMC"
author = "Spherico Hub"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "431ff01c353dc717eef4080a44f9db698ac684fecfb2a4afd721d4655ecf7523"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
