name = "SphericoMC"
author = "Spherico Hub Contributors"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe74eb5fb5459dfae3a9f2d83ce8914bf1847a48bc4f94fed4ea9d0b325fbfc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
